title: Nikos Archontas
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: I am an expert in Better Regulation and in particular in Stakeholder Engagement. Since 2018, I have been working on European Commission's evaluations, impact assessments and stakeholder consultations. 
As Bellevue programme fellow in the SGMAP (2016-2017), I had the opportunity to work in the French public administration and deal with a different and challenging administrative and e-government context. 
As team leader and project manager, working in the Greek Ministry of Interior (2002-2016), I had the opportunity to lead several political and technical structural reform and e-government projects aiming at the modernisation of the Greek public administration. 
The administrative reform process is a magnificent ‘journey’ full of excitement, setbacks but also of great achievements which better the lives of the European citizens.
  <a href="https://www.linkedin.com/in/nikos-archontas-5a9a90234/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
